print("my name is kakhi")
print("hello world")
print("my surename is managadze")
print("i am nine years old")
print("my best friends name is nick")
print("i relly love my family")                     
print("my hight is 142 sentemetres")
print("my phone is an android")
print("my favorite fruit is an apple")
print("my favorite sport is football")
print("goa is best")
print("my favorite juice is pinaple juice")
print("i relly thank my parents for letting me join goa")
print("my best friend is 11 years old")
print("my mum is 37 years old")
print("i was born in italy")
print("my dad works italy")
print("i love my parents")
print("im good student")
print("goa is amazing")
from turtle import *
speed(7)
begin_fill()
forward(200)
left(90)
forward(200)
left(90)
forward(100)
left(90)
forward(90)
right(90)
forward(50)
right(90)
forward(90)
left(90)
forward(90)
left(90)
forward(90)
right(90)
forward(50)
right(90)
forward(90)
left(90)
forward(90)
left(90)
forward(200)
left(90)
forward(175)
left(90)
forward(90)
right(90)
forward(50)
right(90)
forward(90)
exitonclick()
